# Generated by Django 4.0.2 on 2022-02-15 15:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userType', models.CharField(choices=[('Customer', 'Customer'), ('Vendor', 'Vendor')], max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('email', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
                ('createdTs', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
