# Generated by Django 4.0.2 on 2022-02-15 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=30)),
                ('productImageURL', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('productQuantity', models.IntegerField()),
                ('productDescription', models.CharField(max_length=100)),
                ('productUnit', models.CharField(max_length=20)),
                ('createdTs', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
