# Generated by Django 4.0.2 on 2022-02-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productStatus',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
