# Generated by Django 4.0.2 on 2022-02-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImageURL',
            field=models.CharField(max_length=80),
        ),
    ]
