# Generated by Django 4.0.2 on 2022-02-17 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_productstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('productId', models.IntegerField()),
                ('customerId', models.IntegerField()),
                ('vendorId', models.IntegerField()),
                ('orderNumber', models.IntegerField()),
                ('orderedProductQuantity', models.IntegerField()),
                ('orderedProductUnits', models.IntegerField()),
                ('status', models.CharField(choices=[('In process', 'In process'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=15)),
                ('createdTs', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
