# Generated by Django 4.0.2 on 2022-02-18 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('orderId', models.IntegerField()),
                ('productId', models.IntegerField()),
                ('comment', models.CharField(max_length=150)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('status', models.BooleanField()),
                ('createdTs', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='orderedProductUnits',
            field=models.CharField(max_length=10),
        ),
    ]
