# Generated by Django 4.0.2 on 2022-02-18 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_review_alter_order_orderedproductunits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='orderId',
        ),
    ]
